blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.blog, name='blog'),
    path('blog-post/<int:pk>/', views.blogpost, name='blog-post'),
]

catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #path('', views.catalog, name='catalog'),
    path('bus-tours/est/', views.bustours_est, name='bustours-est'),
    path('bus-tours/lv/', views.bustours_lv, name='bustours-lv'),
    path('bus-tours/lt/', views.bustours_lt, name='bustours-lt'),
    path('bus-tours/ru/', views.bustours_ru, name='bustours-ru'),
    path('cruises/', views.cruises, name='cruises'),
    path('bus-tour/<int:pk>/', views.bustour_page, name='bustour-page'),
    path('cruise/<int:pk>/', views.cruise_page, name='cruise-page'),
    path('bus-tour/<int:pk>/book', views.bustour_book, name='bustour-book'),
    path('cruise/<int:pk>/book', views.cruise_book, name='cruise-book'),
]

travelagency/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from users import views as user_views
from orders.views import (
    checkout,
    payment,
    orders,
    order_done
)
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/news-edit/', user_views.NewsEditListView.as_view(), name='news-edit'),
    path('admin/blog-edit/', user_views.BlogEditListView.as_view(), name='blog-edit'),
    path('admin/catalog-list/', user_views.catalog_list, name='catalog-list'),
    path('admin/bustours-edit/', user_views.BusTourEditListView.as_view(), name='bustours-edit'),
    path('admin/cruises-edit/', user_views.CruiseEditListView.as_view(), name='cruises-edit'),
    path('admin/managers-edit/', user_views.managers_list, name='managers-edit'),
    path('admin/news-post/<int:pk>/delete/', user_views.NewsPostDeleteView.as_view(), name='news-post-delete'),
    path('admin/blog-post/<int:pk>/delete/', user_views.BlogPostDeleteView.as_view(), name='blog-post-delete'),
    path('admin/bus-tour/<int:pk>/delete/', user_views.BusTourDeleteView.as_view(), name='bus-tour-delete'),
    path('admin/cruise/<int:pk>/delete/', user_views.CruiseDeleteView.as_view(), name='cruise-delete'),
    path('admin/manager/<int:pk>/delete/', user_views.manager_confirm_delete, name='manager-delete'),
    path('admin/news-post/create', user_views.newspost_create, name='news-post-create'),
    path('admin/blog-post/create', user_views.blogpost_create, name='blog-post-create'),
    path('admin/bus-tour/create', user_views.bustour_create, name='bus-tour-create'),
    path('admin/cruise/create', user_views.cruise_create, name='cruise-create'),
    path('admin/manager/create', user_views.manager_create, name='manager-create'),
    path('orders-edit/', orders, name='orders-edit'),
    path('order/<int:pk>/done', order_done, name='order-done'),
    path('', include('mainapp.urls')),
    path('blog/', include('blog.urls')),
    path('catalog/', include('catalog.urls')),
    path('cart/', include('carts.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('accounts/profile/', user_views.profile, name='profile'),
    path('checkout/', checkout, name='checkout'),
    path('payment/', payment, name='payment'),
    path('tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()


catalog/models.py
from django.db import models
from datetime import date
from django.urls import reverse


# Define choices for Category field
BUSTOUR = 'BUS TOUR'
CRUISE = 'CRUISE'
# A list of tuples. First element of the tuple is an actual value
# to be set on the model field, and the second one is a human-readable name 
CATEGORY_CHOICES = [
    (BUSTOUR, 'Автобусный тур'),
    (CRUISE, 'Круиз'),
]

# Define choices for Country field 
EST = 'EST'
LV = 'LV'
LT = 'LT'
RU = 'RU'
COUNTRY_CHOICES = [
    (EST, 'Эстония'),
    (LV, 'Латвия'),
    (LT, 'Литва'),
    (RU, 'Россия'),
]


class TourDate(models.Model):
    tour_date = models.DateField(default=date.today, verbose_name='Дата тура')
    
    def __str__(self):
        return self.tour_date.strftime('%d %B %Y')


    def is_passed(self):
        return self.tour_date < date.today()


    class Meta:
        ordering = ['tour_date']
        db_table = 'Tour_date'
        verbose_name = 'Расписание тура'
        verbose_name_plural = 'Расписание туров'


class Service(models.Model):
    name = models.CharField(max_length=255, verbose_name='Название')
    notes = models.TextField(blank=True, verbose_name='Примечания')
    price = models.PositiveIntegerField(verbose_name='Цена')


    def __str__(self):
        return self.name


    class Meta:
        db_table = 'Services'
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'


# Abstract base class
# used to store general info about bus tours and cruises
class Tour(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='Название')
    description = models.TextField(blank=True, verbose_name='Описание')
    image = models.ImageField(default='catalog_pics/tour-default-image.png',
                              upload_to='catalog_pics',
                              verbose_name='Путь к картинке')
    timeline = models.TextField(verbose_name='Программа тура')
    charges = models.TextField(verbose_name='Стоимость тура')
    price = models.PositiveIntegerField(verbose_name='Цена')
    n_days = models.PositiveIntegerField(default=1, verbose_name='Количество дней')
    group_size = models.PositiveSmallIntegerField(default=25, verbose_name='Количество мест')
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=BUSTOUR, verbose_name='Категория')
    tourdates = models.ManyToManyField(TourDate, verbose_name='Даты тура')
    services = models.ManyToManyField(Service, blank=True, null=True, verbose_name='Услуги')

    def __str__(self):
        return self.title


    def get_tour_dates(self):
        """return days when the tour is happening"""
        tour_dates = self.tourdates.all()
        if tour_dates.exists():
            return tour_dates
        return []


    def get_services(self):
        services = self.services.all()
        if services.exists():
            return services
        return []

    
    class Meta:
        abstract = True
        ordering = ['title']


class BusTour(Tour):
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=BUSTOUR, verbose_name='Категория')
    country = models.CharField(max_length=5, choices=COUNTRY_CHOICES, verbose_name='Страна')
    

    def get_absolute_url(self):
        """return the unique URL for each blog post"""
        return reverse('bus-tour', kwargs={'pk': self.pk})


    class Meta(Tour.Meta):
        db_table = 'Bus_tour'
        verbose_name = 'Автобусный тур' 
        verbose_name_plural = 'Автобусные туры'


class Ferry(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name='Название')
    link = models.URLField(blank=True, verbose_name='Ссылка на офиц. страницу')


    def __str__(self):
        return self.name

    class Meta:
        db_table = 'Ferry'
        verbose_name = 'Паром'
        verbose_name_plural = 'Паромы'


class Cabin(models.Model):
    category = models.CharField(max_length=50, verbose_name='Класс каюты')
    description = models.TextField(blank=True, verbose_name='Описание')
    image = models.ImageField(default='catalog_pics/cabin-default-image.png',
                              upload_to='catalog_pics', verbose_name='Путь к картинке')
    price = models.PositiveIntegerField(verbose_name='Цена')
    n_passengers = models.SmallIntegerField(verbose_name='Число пассажиров')
    ferry = models.ForeignKey(Ferry, on_delete=models.CASCADE, related_name='cabins',verbose_name='Паром')

    def __str__(self):
        return f'{self.ferry.name}: {self.category}'


    class Meta:
        db_table = 'Cabin'
        verbose_name = 'Каюта'
        verbose_name_plural = 'Каюты'


CITIES_TO_COUNTRIES = {
    'Таллин': 'Эстония',
    'Рига': 'Латвия',
    'Хельсинки': 'Финляндия',
    'Стокгольм': 'Щвеция',
}


class Cruise(Tour):
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default=CRUISE, verbose_name='Категория')
    ferry = models.ForeignKey(Ferry, on_delete=models.CASCADE, verbose_name='Паром')
    n_days = models.PositiveIntegerField(default=2, verbose_name='Количество дней')


    def get_absolute_url(self):
        """return the unique URL for each blog post"""
        return reverse('cruise', kwargs={'pk': self.pk})

    def get_countries(self):
        countries = ''
        city1, city2 = self.title.split(' - ')
        for key, val in CITIES_TO_COUNTRIES.items():
            if city1 == key:
                countries += val + ', '
            elif city2 == key:
                countries += val

        return countries


    class Meta(Tour.Meta):
        db_table = 'Cruise'
        verbose_name = 'Круиз'
        verbose_name_plural = 'Круизы'




catalog/forms.py
from django import forms
from .models import BusTour, Cruise
from tinymce import TinyMCE


class TinyMCEWidget(TinyMCE):

    def use_required_attribute(self, *args):
        return False


class BusTourForm(forms.ModelForm):
    description = forms.CharField(
        label='Описание',
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )
    
    timeline = forms.CharField(
        label='Программа тура',
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    charges = forms.CharField(
        label='Стоимость тура',
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )


    class Meta:
        model = BusTour
        fields = [
            'title', 'description', 'price',
            'country', 'tourdates', 'timeline',
            'charges', 'group_size', 'image'
        ]
        
    


class CruiseForm(BusTourForm):
    class Meta:
        model = Cruise
        fields = [
            'title', 'description', 'price',
            'tourdates', 'timeline', 'charges',
            'group_size', 'image'
        ]
    

class FilterForm(forms.Form):
    price = forms.IntegerField(label='Стоимость', widget=forms.NumberInput(attrs={'type':'range', 'step': '1', 'min': 500, 'max': 15000}))
    n_days = forms.IntegerField(label='Продолжительность', widget=forms.NumberInput(attrs={'type':'range', 'step': '1', 'min': 1, 'max': 7}))

    price.widget.attrs.update({'class': 'form-control'})

catalog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import BusTour, Cruise, Service
from .forms import FilterForm


# Create your views here.
def bustours_est(request):
    tours = BusTour.objects.filter(country='EST', category='BUS TOUR')

    if request.method == 'GET':
        form = FilterForm(data=request.GET)
        if form.is_valid():
            pass
        else:
            pass
    else:
        form = FilterForm(initial={'price': 500, 'duration': 1})

    return render(request, 'catalog/tours-list.html', {'tours': tours, 'form': form})


def bustours_lv(request):
    tours = BusTour.objects.filter(country='LV', category='BUS TOUR')

    if request.method == 'GET':
        form = FilterForm(data=request.GET)
        if form.is_valid():
            pass
        else:
            pass
    else:
        form = FilterForm(initial={'price': 500, 'duration': 1})

    return render(request, 'catalog/tours-list.html', {'tours': tours, 'form': form})


def bustours_lt(request):
    tours = BusTour.objects.filter(country='LT', category='BUS TOUR')

    if request.method == 'GET':
        form = FilterForm(data=request.GET)
        if form.is_valid():
            pass
        else:
            pass
    else:
        form = FilterForm(initial={'price': 500, 'duration': 1})

    return render(request, 'catalog/tours-list.html', {'tours': tours, 'form': form})


def bustours_ru(request):
    tours = BusTour.objects.filter(country='RU', category='BUS TOUR')

    if request.method == 'GET':
        form = FilterForm(data=request.GET)
        if form.is_valid():
            pass
        else:
            pass
    else:
        form = FilterForm(initial={'price': 500, 'duration': 1})

    return render(request, 'catalog/tours-list.html', {'tours': tours, 'form': form})


def cruises(request):
    tours = Cruise.objects.filter(category='CRUISE')

    if request.method == 'GET':
        form = FilterForm(data=request.GET)
        if form.is_valid():
            pass
        else:
            pass
    else:
        form = FilterForm(initial={'price': 500, 'duration': 1})

    return render(request, 'catalog/tours-list.html', {'tours': tours, 'form': form})


def bustour_page(request, pk):
    bustour = BusTour.objects.get(id=pk)
    return render(request, 'catalog/tour-page.html', {'tour': bustour})


def cruise_page(request, pk):
    cruise = Cruise.objects.get(id=pk)
    return render(request, 'catalog/tour-page.html', {'tour': cruise})


@login_required
def bustour_book(request, pk):
    bustour = BusTour.objects.get(id=pk)
    return render(request, 'catalog/tour-book.html', {'tour': bustour})

@login_required
def cruise_book(request, pk):
    cruise = Cruise.objects.get(id=pk)
    return render(request, 'catalog/tour-book.html', {'tour': cruise})




catalog/templates/catalog/tour-book.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="row pt-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-12">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <img class="rounded w-100" src="{{ tour.image.url }}" alt="tour-image">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <h2>{{ tour.title }}</h2>
                        <strong>Категория:</strong>
                        <span class="text-muted">{{ tour.get_category_display }}</span><br>
                        {% if tour.category == 'BUS TOUR' %}
                            <strong>Страна:</strong>
                            <span class="text-muted">{{ tour.get_country_display }}</span>
                        {% elif tour.category == 'CRUISE' %}
                            <p>На пароме <strong>{{ tour.ferry.name }}</strong> (<a href="{{ tour.ferry.link }}" target="_blank">подробнее</a>)</p>
                        {% endif %}
                        <div class="pt-3 pb-2">
                            {% if tour.category == 'BUS TOUR' %}
                                <form action="{% url 'bustour-add-to-cart' tour.id %}" method="POST">
                            {% else %}
                                <form action="{% url 'cruise-add-to-cart' tour.id %}" method="POST">
                            {% endif %}
                                {% csrf_token %}
                                <div class="form-group">
                                    <label><strong>Выберите дату:</strong></label>
                                    <div class="d-flex">
                                        {% for entry in tour.get_tour_dates %}
                                        {% if not entry.is_passed %}
                                        <div class="pr-4 radio-button">
                                            <label>
                                                <input class="" type="radio" name="date"
                                                    value="{{ entry.id }}">
                                                <span
                                                    class="btn btn-outline-primary">{{ entry.tour_date|date:'d.m' }}
                                                </span>
                                            </label>
                                        </div>
                                        {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                                {% if tour.category == 'CRUISE' %}
                                <div class="form-group">
                                    <label><strong>Выберите класс каюты:</strong></label>
                                    <table class="table mb-5">
                                        <tbody>
                                            <tr>
                                                {% for cabin in tour.ferry.cabins.all %}
                                                <td>{{ cabin.category }}</td>
                                                {% endfor %}
                                            </tr>
                                            <tr>
                                                {% for cabin in tour.ferry.cabins.all %}
                                                <td>{{ cabin.price }} руб.</td>
                                                {% endfor %}
                                            </tr>
                                            <tr>
                                                {% for cabin in tour.ferry.cabins.all %}
                                                <td>
                                                    <div class="form-check text-center">
                                                        {% if forloop.counter == forloop.first %}
                                                        <input class="form-check-input cabinOption" type="radio" name="cabin" value="{{ cabin.id }}-{{ cabin.price }}" checked>
                                                        {% else %}
                                                        <input class="form-check-input cabinOption" type="radio" name="cabin" value="{{ cabin.id }}-{{ cabin.price }}">
                                                        {% endif %}
                                                    </div>
                                                </td>
                                                {% endfor %}
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                {% endif %}
                                {% if tour.get_services %}
                                    <div class="form-group">
                                        <label><strong>Выберите дополнительные услуги:</strong></label>
                                        {% for entry in tour.get_services %}
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" name="service {{ forloop.counter }}" value="{{ entry.id }}-{{ entry.price }}">
                                            <label class="form-check-label">
                                                {{ entry.name }}
                                                {% if entry.notes %}
                                                    <p class="text-justify text-muted">{{ entry.notes }}</p>
                                                {% endif %}
                                                <p>
                                                    <strong>Цена:</strong>
                                                    <span class="text-muted">{{ entry.price }} руб.</span>
                                                </p>
                                                
                                            </label>
                                        </div>
                                        {% endfor %}
                                    </div>
                                    <h4 class="mb-3">Итоговая стоимость: <span id="total">{{ tour.price }}</span> руб.</h4>
                                {% endif %}
                                <button class='btn btn-primary' type="submit">Добавить в корзину</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
<script>
    var ititialPrice = null;
    var anyServices = function() {
        var bool = false
        $('input[type="checkbox"]').each(function() {
            if ($(this).prop("checked") == true) {
                bool = true;
                return (bool !== true);
            }
        });
        return bool
    }

    $('input[type="checkbox"]').click(function () {
        // Pull up the total sum at the moment of clicking on checkbox
        var totalSum = $('#total').text();
        totalSum = parseFloat(totalSum);
        // Extract value of checkbox we clicked on
        var inputName = $(this).val().split("-");
        var inputValue = parseFloat(inputName[1]);
        if ($(this).prop("checked") == true) {
            totalSum += inputValue
        }
        else {
            totalSum -= inputValue
        }
        $('#total').text(totalSum);
    });

    $('input[type="radio"].cabinOption').click(function() {
        var totalSum = $('#total').text();
        var inputName = $(this).val().split("-");
        var inputValue = parseFloat(inputName[1]);
        
        if ($(this).prop("checked") == true && anyServices()) {
            totalSum -= initialPrice;
            totalSum += inputValue;
            initialPrice = inputValue;
        }
        else if ($(this).prop("checked") == true) {
            totalSum = inputValue;
            initialPrice = inputValue;
        }
        $('#total').text(totalSum);
    });

    
</script>
{% endblock %}

catalog/templates/catalog/tour-page.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="row pt-4">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-12">
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <img class="rounded w-100" src="{{ tour.image.url }}" alt="tour-image">
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <h2>{{ tour.title }}</h2>
                        <strong>Категория:</strong>
                        <span class="text-muted">{{ tour.get_category_display }}</span>
                        {% if tour.category == 'CRUISE' %}
                            <p>На пароме <strong>{{ tour.ferry.name }}</strong> (<a href="{{ tour.ferry.link }}" target="_blank">подробнее</a>)</p>
                        {% endif %}
                        <div class="d-flex justify-content-start">
                            {% for entry in tour.get_tour_dates %}
                                {% if not entry.is_passed %}
                                    <div class="btn btn-primary mt-2 mb-2 mr-2">{{ entry.tour_date|date:'d.m' }}</div>
                                {% endif %}                            
                            {% endfor %}
                        </div>
                        {% if tour.category == 'CRUISE' %}
                            <h4 class="pt-2">от {{ tour.price }} руб.</h4>
                        {% else %}
                            <h4 class="pt-2">{{ tour.price }} руб.</h4>
                        {% endif %}
                        <p class="text-muted">{{ tour.description|safe}}</p>
                    </div>
                </div>
                <div class="d-flex justify-content-end pb-4">
                    {% if tour.category == 'BUS TOUR' %}
                        <a href="{% url 'bustour-book' tour.id %}" class="btn btn-outline-primary btn-lg">Забронировать</a>
                    {% else %}
                        <a href="{% url 'cruise-book' tour.id %}" class="btn btn-outline-primary btn-lg">Забронировать</a>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="container">
                        <ul class="nav nav-pills bg-light text-center w-100" id="panel" role="tablist">
                            <li class="nav-item rounded border w-50">
                              <a class="nav-link active" id="tour-timeline-tab" data-toggle="pill" href="#tour-timeline" role="tab" aria-controls="pills-tour-outline" aria-selected="true">Программа тура</a>
                            </li>
                            <li class="nav-item rounded border w-50">
                              <a class="nav-link" id="charges-tab" data-toggle="pill" href="#charges" role="tab" aria-controls="pills-charges" aria-selected="false">Стоимость тура</a>
                            </li>
                          </ul>
                          <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="tour-timeline" role="tabpanel" aria-labelledby="tour-timeline-tab">
                                <div class="pt-4">
                                    {{ tour.timeline|safe }}
                                </div>
                            </div>
                            <div class="tab-pane fade" id="charges" role="tabpanel" aria-labelledby="charges-tab">
                                {% if tour.category == 'CRUISE' %}
                                <div class="pt-4">
                                    <h3 class="pb-2">Каюты:</h3>
                                    {% for cabin in tour.ferry.cabins.all %}
                                        <div class="row">
                                            <div class="col-lg-9 col-md-10 col-sm-12 pb-4">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-12">
                                                        <img class="rounded w-100" src="{{ cabin.image.url }}" alt="cabin-image">
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-12">
                                                        <h3>{{ cabin.category }}</h3>
                                                        <p>{{ cabin.description|safe }}</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-lg-2 offset-lg-1 col-md-2 col-sm-12 pb-4">
                                            <h5>{{ cabin.price }} руб.</h5>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                                {% endif %}
                                <div class="">
                                    {{  tour.charges|safe }}
                                </div>
                            </div>
                          </div>
                    </div>
                    
                </div>
               
            </div>
        </div>
    </div>
</div>
{% endblock content%}

catalog/templates/catalog/tours-list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div class="row mt-4">
    <div class="container mb-4">
        <div class="row">
            <div class="col-lg-8 col-md-9">
                <div class='mb-4'>
                    <form action="#" method="POST" class="row">
                        <div class="col-lg-10 col-md-8">
                            <input class="form-control form-control-lg" type="text" placeholder="Введите название тура">
                        </div>
                        <div class="col-lg-2 col-md-4">
                            <div class="float-right">
                                <button type="submit" class="btn btn-lg btn-primary">Поиск</button>
                            </div>
                        </div>
                    </form>
                </div>
                
                <div class="row">
                    {% for tour in tours %}
                    <div class="col-lg-6 col-md-6 col-sm-auto" style="padding-bottom: 20px; transition: 0.5s">
                        <div class="card hover-effect h-100">
                            <img class="card-img-top" src="{{ tour.image.url }}" alt="Card image cap">
                            <div class="card-body">
                                <div class="h-50">
                                    {% if tour.category == 'BUS TOUR' %}
                                        <h4 class="card-title"><a class="info-link" href="{% url 'bustour-page' tour.id %}">{{ tour.title }}</h4></a>
                                    {% else %}
                                        <h4 class="card-title"><a class="info-link" href="{% url 'cruise-page' tour.id %}">{{ tour.title }}</h4></a>
                                    {% endif %}
                                </div>
                                <p class="float-left text-muted">{{ tour.get_category_display }}</p>
                                <h5 class="card-text text-right">{{ tour.price }} руб.</h5>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-3">
                <form action="" method="GET">
                   <input type="range" min="1" max="7" value="1" id="durationRange" name="duration" class="slider">

                    <button type="submit" class="btn btn-primary">Применить</button>
                    
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content%}